name: Generate and Deploy Doxygen Docs

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen graphviz

    - name: Install Doxygen-awesome-css
      run: git submodule add https://github.com/jothepro/doxygen-awesome-css.git &&
            cd doxygen-awesome-css &&
            git checkout v2.3.4 &&
            cd ..

    - name: Generate Doxygen documentation
      run: doxygen Doxyfile

    - name: Create .nojekyll file
      run: touch ./html/.nojekyll

    - name: Move HTML content to root
      run: mv ./html/* ./

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        destination_dir: .

